### ISSUE TITLE
It is possible to remove the www.?

### ISSUE THREAD

**Issue by Neustradamus** [audacity/audacity.github.io#19]
Dear @audacity team,

It is possible to remove the www. to have the website https://audacityteam.org/?

To redirect to https://audacityteam.org/*:
- http://www.audacityteam.org/*
- https://www.audacityteam.org/*
- http://audacityteam.org/*

Thanks in advance.

**Comment by LWinterberg** [comment]
Is there a concrete need for or benefit to this? The redirect the other way round works fine for me, both in browsers and CL tools like lynx and wget.

**Comment by Neustradamus** [comment]
@LWinterberg: Sorry for the delay!

Better SEO...

And the "www." is not needed in 2024.

**Comment by Neustradamus** [comment]
In more, do not forget to create a news for each release.

For example, the latest is 3.4:
- https://www.audacityteam.org/blog/audacity-3-4

**Comment by LWinterberg** [comment]
> Better SEO...

www vs apex has no difference as far as SEO is concerned. Switching from one to the other does though, and since we didn't want to disrupt any ranking, we kept all links the same. 

> And the "www." is not needed in 2024.

correct, hence why it automatically redirects. 

> In more, do not forget to create a news for each release. For example, the latest is 3.4

3.4 is the latest release available. There are some patches following it, which get distributed via the updater and changelog, but which aren't terribly relevant for people visiting the website.

**Comment by Neustradamus** [comment]
@LWinterberg: Currently there is a 3.4.2... The latest version which must be downloaded by people...

Announcement must be at one place.

Badly when I announce Audacity new release, I need to use GitHub link instead of the official announcement.

**Comment by LWinterberg** [comment]
You also can link to the [changelog](https://support.audacityteam.org/additional-resources/changelog/audacity-3.4.2) for patch releases. The blog on the website is not the release feed.
